# Generated by Django 4.1.6 on 2023-02-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Purchases', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sales', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
