# Generated by Django 4.1.7 on 2023-02-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('c', 'Complated'), ('w', 'Waiting'), ('p', 'On progress')], default='w', max_length=1),
        ),
    ]
