# Generated by Django 4.1.5 on 2023-01-30 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('gear', models.CharField(choices=[('A', 'automatic'), ('M', 'manuel')], max_length=1)),
                ('rent_per_day', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)])),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
