# Generated by Django 4.1.6 on 2023-04-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_course_id_alter_courses_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
