# Generated by Django 4.1.6 on 2023-04-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='courses',
        ),
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='courses.courses'),
        ),
    ]
