# Generated by Django 4.1.6 on 2023-04-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_students_courses_students_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
