# Generated by Django 4.1.6 on 2023-04-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_students_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(to='courses.courses'),
        ),
    ]
