# Generated by Django 4.1.5 on 2023-04-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_bio_remove_profile_display_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='case',
            new_name='purse',
        ),
    ]
